apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deploy
  labels:
    env: gowtham
    owner: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      env: gowtham
      owner: prod
  template:
    metadata:
      labels:
        env: gowtham
        owner: prod
    spec:
      containers:
        - name: cat-deploy
          image: kgowtham12/project-1:v1
          ports:
            - containerPort: 8080
